name: Mirror Repository

on:
  push:
    branches:
      - main
env:
  MIRROR_URL: git@github.com:EpitechPromo2027/G-EIP-600-STG-6-1-eip-noe.tritsch.git

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'augustin-grosnon/ufeel-testing-room'
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Mirroring repository
      uses: pixta-dev/repository-mirroring-action@v1
      with:
        target_repo_url: ${{ env.MIRROR_URL }}
        ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}