name: Mirror Repository

on:
  push:
    branches:
      - '**'

env:
  MIRROR_URL: git@github.com:EpitechPromo2027/G-EIP-600-STG-6-1-eip-noe.tritsch.git

jobs:
  push_to_mirror:
    runs-on: ubuntu-latest
    if: github.repository == 'augustin-grosnon/ufeel-testing-room'
    steps:

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.GIT_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - name: Push to Mirror Repository
      run: |
        git remote add mirror $MIRROR_URL
        git push mirror --all
        git push mirror --tags
